---
title: "NFL Attendance"
output: html_document
date: "2024-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(ggthemes)
theme_set(theme_light())
```

```{r}
attendance <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv')
standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv')
games <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/games.csv')

attendance_joined <- attendance %>% 
  left_join(standings,
            by = c("year", "team_name", "team"))

```

## EDA
```{r}
attendance_joined %>% 
  filter(!is.na(weekly_attendance)) %>% 
  ggplot(aes(fct_reorder(team_name, weekly_attendance), weekly_attendance, fill = playoffs)) + 
  geom_boxplot(outlier.alpha = .5) +
  coord_flip()

```

```{r}
attendance_joined %>% 
  distinct(team_name, year, margin_of_victory, playoffs) %>% 
  ggplot(aes(margin_of_victory, fill = playoffs)) + 
  geom_histogram(position = "identity",alpha = .7)

```

```{r}
attendance_joined %>% 
  mutate(week = factor(week)) %>% 
  ggplot(aes(week, weekly_attendance, fill = week)) + 
  geom_boxplot(show.legend = F, outlier.alpha = .4) + 
  coord_flip()

```

## build a df for modeling
```{r}
attendance_df <- attendance_joined %>% 
  filter(!is.na(weekly_attendance)) %>% 
  select(weekly_attendance, team_name, year, week, margin_of_victory, strength_of_schedule, playoffs)

```

```{r}
set.seed(1234)

attendance_split <- attendance_df %>% 
  initial_split(strata = playoffs)

training_set <- training(attendance_split)
testing_set <- testing(attendance_split)

```

```{r}
#linear regression
lm_spec <- linear_reg() %>% 
  set_engine("lm")

lm_fit <- lm_spec %>% 
  fit(weekly_attendance ~ ., 
      data = training_set)

lm_fit %>% 
  tidy() %>% 
  arrange(-estimate)


```

```{r}
# random forest
rf_spec <- rand_forest(mode = "regression") %>% 
  set_engine("ranger")

rf_fit <- rf_spec %>% 
    fit(weekly_attendance ~ ., 
      data = training_set)

```

# evaluate the models
```{r}
results_train <- lm_fit %>% 
  predict(new_data = training_set) %>% 
  mutate(truth = training_set$weekly_attendance, 
         model = "lm") %>% 
  bind_rows(rf_fit %>% 
  predict(new_data = training_set) %>% 
  mutate(truth = training_set$weekly_attendance, 
         model = "rf"))

results_test <- lm_fit %>% 
  predict(new_data = testing_set) %>% 
  mutate(truth = testing_set$weekly_attendance, 
         model = "lm") %>% 
  bind_rows(rf_fit %>% 
  predict(new_data = testing_set) %>% 
  mutate(truth = testing_set$weekly_attendance, 
         model = "rf"))

```

```{r}
results_train %>% 
  group_by(model) %>% 
  rmse(truth = truth, estimate = .pred)

results_test %>% 
  group_by(model) %>% 
  rmse(truth = truth, estimate = .pred)

```

```{r}
results_test %>% 
  mutate(type = "testing") %>% 
  bind_rows(results_train %>% 
              mutate(type = "training")) %>% 
  mutate(type = factor(type, levels = c("training", "testing"))) %>%
  ggplot(aes(truth, .pred, color = model))+
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_point(alpha = .5) +
  facet_wrap(~type)
```

## let's try another approach with resampling to improve the rf model

```{r}
set.seed(2345)

nfl_folds <- vfold_cv(training_set, strata = playoffs)

rf_workflow <- workflow() %>%
  add_model(rf_spec) %>%
  add_formula(weekly_attendance ~ .)

# Define the workflow
rf_workflow <- workflow() %>%
  add_model(rf_spec) %>%
  add_formula(weekly_attendance ~ .)

# Fit resamples with the workflow
rf_results <- fit_resamples(
  rf_workflow,
  resamples = nfl_folds,
  control = control_resamples(save_pred = TRUE)
)

```

```{r}
rf_results %>% 
  collect_metrics()

results_test %>% 
  group_by(model) %>% 
  rmse(truth = truth, estimate = .pred)

```

# Visualize the predictions
```{r}
rf_results %>% 
  unnest(.predictions) %>% 
  ggplot(aes(weekly_attendance, .pred, color = id)) + 
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_point(alpha = .5)
```

# Additional work beyond the tutorial - exploring ggplot add'l packages

```{r}
library(ggfx)
library(gghighlight)

df_chart <- attendance_joined %>% 
  select(team_name, weekly_attendance, week) %>% 
  filter(!is.na(weekly_attendance)) %>%
  group_by(team_name, week) %>% 
  summarize(avg_attendance = mean(weekly_attendance)) %>%
  ungroup()

df_chart %>%
  filter(week %in% c(1, 17)) %>%
  pivot_wider(names_from = week, values_from = avg_attendance, names_prefix = "week_") %>%
  mutate(discrepancy = abs(week_17 - week_1)) %>%
  arrange(desc(discrepancy))

df_static <- df_chart %>% 
  filter(!team_name %in% c("Browns", "Eagles")) %>%
  mutate(static_week = week) %>%  # Rename 'week' for static lines
  select(-week)  # Remove original 'week' column

df_animated <- df_chart %>% filter(team_name %in% c("Browns", "Eagles"))

```

```{r}
library(ggrepel)
library(gganimate)
library(ggtext)

browns_color <- "#c35d2f"
eagles_color <- "#087f25"

for_plot <- ggplot(df_animated, aes(x = week, y = avg_attendance, color = team_name)) +
  ggthemes::theme_economist(base_size = 10) +
  theme(plot.margin = margin(t = 2, l = 5, unit = 'mm')) +
  
  # Static lines for other teams (non-animated)
  geom_line(aes(x = static_week), data = df_static, size = 1, show.legend = FALSE) +
  
  # Animated lines for Browns and Eagles
  geom_line(size = 1.5, 
    show.legend = FALSE) +  
  
  # Outer glow effect for Browns and Eagles
  with_outer_glow(
    geom_line(
      data = df_animated %>% filter(team_name == "Browns"),
      aes(x = week, y = avg_attendance), 
      size = 1.5
    ),
    colour = "#fda77e",
    sigma = 5,
    expand = 2
  ) +
  with_outer_glow(
    geom_line(
      data = df_animated %>% filter(team_name == "Eagles"),
      aes(x = week, y = avg_attendance), 
      size = 1.5
    ),
    colour = "#03b32e",
    sigma = 5,
    expand = 2
  ) +
  
  # Custom color scale
  scale_color_manual(values = c("Browns" = browns_color, "Eagles" = eagles_color)) +
  guides(color = "none") +
  scale_y_continuous(labels = label_number(scale = 1 / 1e3, suffix = "k")) +
  scale_x_continuous(breaks = unique(df_chart$week)) +
  
  # Axis labels and title
  labs(
    title = "Largest Average Attendance Difference, 2000 to 2019\n",
    subtitle = '\nWeek: {sprintf("%.0f", frame_along)}',
    x = "\nWeek",
    y = "Attendance\n"
  ) +
  annotate(
    "richtext",
    x = 5,
    y = 78000,
label = sprintf('The <span style="color:%s;"><b>Eagles</b></span> saw the largest increase and the <span style="color:%s;"><b>Browns</b></span> saw the largest decrease.', eagles_color, browns_color),
    hjust = 0, vjust = -1.1,
    size = 5,
    label.color = NA  # Remove label box outline
  ) 

for_plot
```

```{r}
#anim2 <- for_plot + transition_reveal(week)
#animate(anim2,nframes = 120, fps = 10, width = 1200, height = 600, end_pause = 40)
```


### Add'l work beyond tutorial - workflowsets

```{r}

attendance_formodel <- attendance_joined %>% 
    filter(!is.na(weekly_attendance))

attendance_split <- initial_split(attendance_formodel)
attendance_trainingset <- training(attendance_split)
attendance_testingset <- testing(attendance_split)

```

```{r}
recipe_base <- recipe(weekly_attendance ~ ., data=attendance_trainingset) %>% 
  step_rm(team) %>% # remove the other response and ID vars
  step_nzv(all_predictors()) %>%  # remove near-zero variance EVs
  step_zv(all_predictors()) %>%  # remove near-zero variance EVs
  step_corr(all_numeric_predictors()) %>%  # remove highly correlated vars
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal(), one_hot = T) %>% 
  step_impute_knn()

recipe_base %>% prep() %>% juice() %>% glimpse()

recipe_full <- recipe_base  %>% 
  step_impute_mean(all_numeric_predictors())

recipe_full %>% prep() %>% juice() %>% glimpse()
```


```{r}
library(workflowsets)
# Glmnet model
glmnet_spec <- linear_reg(penalty = tune(), mixture = tune()) %>% 
  set_engine("glmnet")

# xgboost
xgboost_spec <- boost_tree(
  mode = "regression",
  trees = 500,
  learn_rate = tune(),
  min_n = tune()
) %>% 
  set_engine("xgboost")

# SVM
svm_spec <- svm_rbf(
  cost = tune(),
  rbf_sigma = tune(),
  margin = tune()) %>% 
  set_engine("kernlab") %>% 
  set_mode("regression")

# resamples
resample_spec <- vfold_cv(attendance_trainingset, v = 5)
#registerDoMC(cores = 4)

workflow_setup <- workflow_set(
  preproc = list(
    base = recipe_base,
    full = recipe_full
  ),
  models = list(
    glmnet = glmnet_spec,
    xgboost = xgboost_spec,
    svm = svm_spec
  ),
  cross = T
)

workflow_setup

library(parallel)
library(doParallel)
library(finetune)
library(xgboost)
library(lme4)
cores <- parallel::detectCores(logical = F)
cores
clusters <- makePSOCKcluster(cores-2)
registerDoParallel(clusters)

set.seed(123)
if (exists("workflowset_tune_results")) rm("workflowset_tune_results")
workflowset_tune_results <- workflow_setup %>% 
  workflow_map(
    fn = "tune_race_anova",
    resamples = resample_spec,
    grid = 15,
    metrics = metric_set(rmse, rsq),
    verbose = T
  )

doParallel::stopImplicitCluster()
library(readr)

#workflowset_tune_results %>% 
#  write_rds("01_results/workflowset_tune_results.rds")
#workflowset_tune_results <- read_rds("01_results/workflowset_tune_results.rds")

autoplot(workflowset_tune_results)

# autoplot(workflowset_tune_results) + 
#   scale_color_tq() + 
#   theme_tq()

workflowset_tune_results %>% 
  rank_results(rank_metric = "rmse") %>% 
  filter(.metric == "rmse")

autoplot(workflowset_tune_results, id = "base_glmnet", metric = "rmse")

```

# Finalize best model
```{r}
# get the parameters of the best model
params_bestmodel <- workflowset_tune_results %>% 
  pull_workflow_set_result(id = "base_glmnet") %>% 
  select_best(metric = "rmse")

# fit to the testing data
workflow_fit_final <- workflowset_tune_results %>% 
  pull_workflow("base_glmnet") %>% 
  finalize_workflow(params_bestmodel) %>% 
  fit(attendance_testingset)

workflow_fit_final

# make predictions
predictions_tbl <- workflow_fit_final %>% 
  predict(new_data = attendance_testingset) %>% 
  mutate(truth = attendance_testingset$weekly_attendance,
         model = "glm")

```

```{r}
predictions_tbl %>% 
  ggplot(aes(truth, .pred)) + 
  geom_point() + 
  geom_abline(slope = 1, intercept = 0, color = "grey")

```

```{r}
library(vip)

importance_tbl <- vip::vi(workflow_fit_final$fit$fit$fit)
importance_tbl

importance_tbl %>% 
  ggplot(aes(Importance, fct_reorder(Variable, Importance), fill = Sign)) + 
  geom_col()
```



